const URL="https://xldnayhoquadguepedqm.supabase.co";const KEY="sb_publishable_EPC6EEnO2EEvcIQFtozteA_XTKMyPx1";const db=supabase.createClient(URL,KEY);let rows=[],selected=null;
const $=x=>document.getElementById(x),today=()=>new Date().toISOString().slice(0,10),num=x=>Number(x||0),fmt=x=>num(x).toLocaleString('en-IN',{maximumFractionDigits:2});
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function load(){let r=await db.from('inventory_stock').select('*').eq('is_active',true).order('product_name');if(r.error)return alert(r.error.message);rows=r.data||[];render()}
function render(){let q=$('search').value.toLowerCase();let a=rows.filter(r=>(r.product_name+' '+r.batch_no+' '+(r.supplier||'')).toLowerCase().includes(q));$('body').innerHTML=a.map(r=>`<tr><td><b>${esc(r.product_name)}</b><br><small>${esc(r.description||'')}</small></td><td>${esc(r.batch_no)}</td><td>${r.entry_date||''}</td><td>${r.expiry_date||'-'}</td><td><b>${fmt(r.current_qty)}</b></td><td>${esc(r.unit)}</td><td>₹${fmt(r.rate)}</td><td>${fmt(r.gst_percent)}%</td><td><button class="rowbtn" onclick="move('${r.id}')">IN / OUT</button><button class="rowbtn gray" onclick="edit('${r.id}')">Edit</button><button class="rowbtn danger" onclick="del('${r.id}')">Delete</button></td></tr>`).join('');$('empty').classList.toggle('hidden',a.length>0);$('products').textContent=rows.length;$('stock').textContent=fmt(rows.reduce((s,r)=>s+num(r.current_qty),0));$('low').textContent=rows.filter(r=>num(r.current_qty)<=num(r.reorder_level)).length;let d=new Date();d.setDate(d.getDate()+30);$('exp').textContent=rows.filter(r=>r.expiry_date&&new Date(r.expiry_date)>=new Date()&&new Date(r.expiry_date)<=d).length}
function openForm(r){$('productModal').classList.remove('hidden');$('mtitle').textContent=r?'Edit Product':'Add Product';$('id').value=r?.id||'';$('name').value=r?.product_name||'';$('desc').value=r?.description||'';$('batch').value=r?.batch_no||'';$('entry').value=r?.entry_date||today();$('expiry').value=r?.expiry_date||'';$('qty').value=r?.current_qty??0;$('unit').value=r?.unit||'Kit';$('pack').value=r?.units_per_pack??'';$('rate').value=r?.rate??0;$('gst').value=r?.gst_percent??0;$('supplier').value=r?.supplier||'';$('reorder').value=r?.reorder_level??0;$('formMsg').textContent=''}
window.edit=id=>openForm(rows.find(r=>r.id===id));$('add').onclick=()=>openForm();$('search').oninput=render;
$('close').onclick=$('cancel').onclick=()=>$('productModal').classList.add('hidden');
$('form').onsubmit=async e=>{e.preventDefault();let p={product_name:$('name').value.trim(),description:$('desc').value.trim()||null,batch_no:$('batch').value.trim(),entry_date:$('entry').value,expiry_date:$('expiry').value||null,current_qty:num($('qty').value),unit:$('unit').value.trim(),units_per_pack:$('pack').value?num($('pack').value):null,rate:num($('rate').value),gst_percent:num($('gst').value),supplier:$('supplier').value.trim()||null,reorder_level:num($('reorder').value),is_active:true};let id=$('id').value;let r=id?await db.from('inventory_stock').update(p).eq('id',id):await db.from('inventory_stock').insert(p);if(r.error)$('formMsg').textContent=r.error.message;else{$('productModal').classList.add('hidden');load()}};
window.del=async id=>{if(!confirm('Delete this product permanently?'))return;let r=await db.from('inventory_stock').delete().eq('id',id);if(r.error)alert(r.error.message);else load()};
window.move=id=>{selected=rows.find(r=>r.id===id);$('moveModal').classList.remove('hidden');$('moveTitle').textContent=selected.product_name+' — Stock';$('current').textContent=fmt(selected.current_qty);$('moveQty').value='';$('moveMsg').textContent=''};
async function movement(type){let q=num($('moveQty').value);if(!q||q<=0){$('moveMsg').textContent='Enter valid quantity.';return}let fn=type==='in'?'stock_in':'stock_out';let r=await db.rpc(fn,{p_inventory_id:selected.id,p_quantity:q});if(r.error){$('moveMsg').textContent=r.error.message;return}$('moveMsg').style.color='#15803d';$('moveMsg').textContent='Updated. Current stock: '+fmt(r.data);setTimeout(()=>{$('moveModal').classList.add('hidden');load()},500)}
$('in').onclick=()=>movement('in');$('out').onclick=()=>movement('out');$('moveClose').onclick=$('moveCancel').onclick=()=>$('moveModal').classList.add('hidden');
$('loginBtn').onclick=async()=>{let r=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(r.error)$('loginMsg').textContent=r.error.message};
$('logout').onclick=()=>db.auth.signOut();
db.auth.onAuthStateChange((e,s)=>{$('login').classList.toggle('hidden',!!s);$('app').classList.toggle('hidden',!s);if(s)load()});db.auth.getSession().then(r=>{if(r.data.session)load()});